import os
import pandas as pd

# ==========================================
# 🛠️ GLOBAL CONFIGURATION & PATH SETUP
# ==========================================
BASE_DIR = os.path.dirname(os.path.abspath(__file__)) if '__file__' in locals() else './'
INPUT_DIR = os.path.join(BASE_DIR, 'LLManalysis')
OUTPUT_DIR = os.path.join(BASE_DIR, 'LLMvisuals')
os.makedirs(OUTPUT_DIR, exist_ok=True)

SUBREDDITS = ['Gaming', 'Smartphones', 'Technology']
LABELS = ['Posts', 'Comments']
MODELS = ['Groq', 'Gemini']


def extract_text_safely(file_path, column_name, default_val):
    if not os.path.exists(file_path):
        return default_val
    try:
        df = pd.read_csv(file_path)
        df.columns = [c.lower() for c in df.columns]
        target_col = column_name.lower()
        if target_col in df.columns and not df.empty:
            # Grab the first valid single row record
            return str(df[target_col].iloc[0]).strip()
    except Exception:
        pass
    return default_val


def generate_markdown_matrix():
    print("==================================================================", flush=True)
    print("🚀 INITIALIZING QUALITATIVE SUBREDDIT COMPARISON ENGINE", flush=True)
    print("==================================================================", flush=True)

    md_content = [
        "# 📊 Subreddit Cross-Community Narrative & Pattern Comparison Matrix",
        "This report aggregates and aligns the high-level macro summaries and recurring linguistic behavioral patterns extracted by the AI engines across the monitored platforms.\n",
    ]

    for label in LABELS:
        md_content.append(f"## 💬 1. Cross-Subreddit Analytical Matrix: {label.upper()}")
        md_content.append(
            "This section compares the structural executive summaries generated by both model engines side-by-side.\n")

        # --- SUBSECTION A: EXECUTIVE SUMMARIES GRID ---
        md_content.append(
            "| Subreddit Community | Groq Engine Summary (100% Sweep Context) | Gemini Engine Summary (Overlapping Slice) |")
        md_content.append("| :--- | :--- | :--- |")

        for sub in SUBREDDITS:
            q_sum_file = os.path.join(INPUT_DIR, f"{sub}_{label}_Groq_Summarization.csv")
            g_sum_file = os.path.join(INPUT_DIR, f"{sub}_{label}_Gemini_Summarization.csv")

            q_summary = extract_text_safely(q_sum_file, 'summary', "No data summary generated.")
            g_summary = extract_text_safely(g_sum_file, 'summary', "Analysis tier skipped.")

            md_content.append(f"| **r/{sub}** | {q_summary} | {g_summary} |")

        md_content.append("\n" + "—" * 40 + "\n")

        # --- SUBSECTION B: LINGUISTIC PATTERNS GRID ---
        md_content.append(f"## 🎯 2. Recurring Behavioral & Discussion Patterns: {label.upper()}")
        md_content.append(
            "A side-by-side extraction mapping out the top 3 persistent linguistic traits and user habits noted by the models.\n")

        md_content.append(
            "| Subreddit Category | Groq Identified Discussion Patterns | Gemini Identified Discussion Patterns |")
        md_content.append("| :--- | :--- | :--- |")

        for sub in SUBREDDITS:
            q_pat_file = os.path.join(INPUT_DIR, f"{sub}_{label}_Groq_Patterns.csv")
            g_pat_file = os.path.join(INPUT_DIR, f"{sub}_{label}_Gemini_Patterns.csv")

            q_patterns = extract_text_safely(q_pat_file, 'patterns', "No distinct patterns found.").replace(" | ",
                                                                                                            "<br><br>")
            g_patterns = extract_text_safely(g_pat_file, 'patterns', "Analysis tier skipped.").replace(" | ",
                                                                                                       "<br><br>")

            md_content.append(f"| **r/{sub}** | {q_patterns} | {g_patterns} |")

        md_content.append("\n\n" + "=" * 60 + "\n\n")

    # Save to disk
    output_file_path = os.path.join(OUTPUT_DIR, "subreddit_narrative_comparison.md")
    with open(output_file_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(md_content))

    print("\n==================================================================", flush=True)
    print("✨ SUCCESS! NARRATIVE COMPARISON DASHBOARD REPORT COMPILED NATIVELY!", flush=True)
    print(f"File saved successfully to: '{output_file_path}'", flush=True)
    print("==================================================================", flush=True)


if __name__ == "__main__":
    generate_markdown_matrix()